//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Database.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1,10,26600,-8800,6100
        ///1,14,19200,8500,28300
        ///1,20,0,0,0
        ///2,8,-24400,-4800,4500
        ///2,25,0,0,0
        ///3,18,-24800,-5500,4600
        ///3,19,5300,3400,7800
        ///3,24,0,0,0
        ///4,15,0,0,0
        ///5,6,5000,7800,13600
        ///5,10,0,0,0
        ///6,5,2500,700,10500
        ///6,7,0,0,0
        ///6,81,-1800,-11900,-13400
        ///7,6,26900,16800,22300
        ///7,8,0,0,0
        ///8,2,10600,16800,16600
        ///8,7,13800,9400,-2300
        ///8,9,0,0,0
        ///9,8,12900,5600,-17000
        ///9,11,25400,11600,1600
        ///9,12,0,0,0
        ///9,13,13100,16800,800
        ///10,1,0,0,0
        ///10,5,-20300,-7700,-15600
        ///11,9,9300,1300,-15100
        ///11,13,0,0,0
        ///12,9,-10000,5100 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string gates {
            get {
                return ResourceManager.GetString("gates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1,Solrain Core,1
        ///2,Solrain Wake,1
        ///3,Solrain Cornea,1
        ///4,Solrain Depot,1
        ///5,The Inner Lighthouse,1
        ///6,The Greater Locks,1
        ///7,The Outer Lighthouse,1
        ///8,Purian Lake,1
        ///9,Morain Harbour,1
        ///10,Wanderer&apos;s Pond,1
        ///11,Tranquillus Major,1
        ///12,The Fields,1
        ///13,The Bronci Rift,1
        ///14,The Sea of Solrain,1
        ///15,Tranquillus Minor,1
        ///16,The Inner Oasis,1
        ///17,Midpoint Rift,1
        ///18,The Outer Oasis,1
        ///19,The Azure Churn,1
        ///20,The Narrow Canal,1
        ///21,The Lesser Locks,1
        ///22,The Cerulean Clouds,1
        ///23,Tribular Canal,1
        ///24,The Outer [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string sectors {
            get {
                return ResourceManager.GetString("sectors", resourceCulture);
            }
        }
    }
}
